site_name: golang开发知识整理
site_author: 'setcreed'
repo_name: 'GoGo'
repo_url: 'https://github.com/setcreed/GoGo'
# theme: readthedocs

# Configuration, https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  # disqus: 'setcreed'
  social:
    - type: 'github'
      link: 'https://github.com/setcreed'

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: true  #for use of inline $..$
  - codehilite: # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
      linenums: true
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.superfences

copyright: 'Copyright &copy; 2019 - 2020 setcreed'

nav:
- 简介: 'index.md'
- Go基础:
    - '00 Golang简介': 'basics/00_golang简介/hello_go.md'
    - '01 Go基础类型': 'basics/01_go_basic_type/go_basic_type.md'
    - '02 Go的控制流程': 'basics/02_go_control/go_control.md'
    - '03 Go的数组和切片': 'basics/03_array_and_slice/array_and_slice.md'
    - '04 Go的映射': 'basics/04_map/map.md'
    - '05 Go的函数': 'basics/05_go_func/go_func.md'
    - '06 Go的包': 'basics/06_go_bao/go_bao.md'
    - '07 Go的指针': 'basics/07_go_pointer/go_pointer.md'
    - '08 GO的结构体': 'basics/08_go_struct/go_struct.md'
    - '09 Go的方法': 'basics/09_go_method/go_method.md'
    - '10 Go的接口': 'basics/10_go_interface/go_interface.md'
